language: python
python: 3.6

jobs:
  include:
    - stage: Lint
      install:
          - pip install pipenv
          - pipenv sync --dev
      script:
        - echo "Validating linting"
        - flake8 .
    - stage: Github release
      script: echo "Releasing to Github"
      deploy:
        provider: releases
        api_key:
          secure: "ZBhTXfzl9WtwTBU49GFIH48Q7Z9rp/zzeQZMD/t2+lz4TfbEgudhyq3runJ+8dxLf5TvFkmQjcvIfvSeVkkIovNb5o+f3Q8hrwSkB4s8LLURtU6GUP7gvAVzc908bE60TmDo5lLVCIRkiVDT0mb52Xrw1nlnwYhS4wjDILDZztzsJoKeFqqtWhlqkr1Bk1/Rr9iMfW49YZlDE15qsZ9sSCxXrWiJgClKmAHicfY7Gncr4KzY7j/SEzEhKg1foQaxIpXo+VasTJ+5qMk6X+ZMWpI/9GU6lt5Pn+D32ULJUNLO3De+Cxbql45JbzvKo7H77vnnHWEu5nQTv6udDOhrUy29fYadcNjLfnty/Zd7qUXf5spLSuK4rlRc04PFtIIAy8+zD80rYmITfxIypl9xIzzc3xig+wIcGwp1VbOx5U8wDD311VN8zmuXeqJpxydIA9MOm0INWY1efK95O++ibVXZJqQe2Na9fJ9WHTVg7SbMHxXhDv6SygewmwsaYITFzyiZsDX4rCqVH1iFS0ikXIUKUHEOW5pVzX71j/Rbn1n1+6s8mrAJaPv1Be1jsVHnvaZufqljlt+GX3S9qLSAItgqBN8nzjU7H8Tgqq2lNKqSIwqHvyc1h7/p5VYWMiWfKg9QdVgL+hwWGJ/cld33rqpfA/LLURlQbZnrYtyZ4S4="
        skip_cleanup: true
        on:
          tags: true
          python: 3.6
